global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'loan-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      # host.docker.internal is used to access the host machine from a container.
      # Only use in local development
      - targets: ['host.docker.internal:8080']

  - job_name: 'fraud-detection'
    metrics_path: '/actuator/prometheus'
    # host.docker.internal is used to access the host machine from a container.
    # Only use in local development
    static_configs:
      - targets: ['host.docker.internal:8081']